name: Release

on:
  workflow_dispatch:
    inputs:
      new_develop_version:
        description: 'New development version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 'develop'
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Remove '-SNAPSHOT'
      run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false --file pom.xml
    - name: Commit changes on develop
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Removed -SNAPSHOT before releasing'
    - name: Merge develop into master
      uses: devmasx/merge-branch@v1.4.0
      with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Output version
      run: echo "MASTER_VERSION=$(mvn -B -N help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Tag master
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ env.MASTER_VERSION }}
    - name: Push master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        tags: true
    - name: Update develop version
      run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.new_develop_version }} -DgenerateBackupPoms=false --file pom.xml
    - name: Commit changes on develop after releasing
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Set new develop version'
    - name: Push develop
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop
