name: Release

on:
  workflow_dispatch:
    inputs:
      new_develop_version:
        description: 'New development version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 'develop'
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Initialize Git environment
      run: |
        git config --global user.name "Gihub deploy action"
        git config --global user.email "<>"
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Remove '-SNAPSHOT' on develop versions
      run: |
        git checkout develop && git pull
        mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false --file pom.xml
        git add --all
        git diff-index --quiet HEAD || git commit -am 'Removed -SNAPSHOT before releasing'
    - name: Merge develop into master
      run: |
        git checkout develop && git pull
        git checkout master && git pull
        git merge develop -Xtheirs -m "Merging develop into master"
    - name: Tag master
      run: |
        git tag -a "v$(mvn -B -N help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)"
    - name: Update version and push develop
      run: |
        git checkout develop
        mvn -B versions:set -DnewVersion=${{ github.event.inputs.new_develop_version }} -DgenerateBackupPoms=false --file pom.xml
        git commit -am "Set new develop version"
    - name: Deploy 'master'
      run: |
        git checkout master
        mvn -B clean deploy -Prelease,deploy --file pom.xml
    - name: Push develop and master
      run: |
        git checkout develop && git push
        git checkout master && git push --tags